In [13]:
import numpy as np


In [2]:
a = np.array([[1, 2, 3], [4, 5, 6] , [7, 8, 9]])

In [3]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
a[0][2]

np.int64(3)

In [42]:
a[0:2,1:3] # a[row_start:row_end, col_start:col_end:step]

array([[2, 3],
       [5, 6]])

In [20]:
a[:, 1:3:2] #-> A[row_start:row_end, col_start:col_end:step] 

array([[2],
       [5],
       [8]])

In [ ]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) 

In [23]:
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [34]:
print(b[0:2,0:2,1:3]) #-> syntax: A[depth:depth_end, row:row_end, column:column_end] depth-> number of 2D arrays, row-> number of rows, column-> number of columns

[[[2]
  [4]]

 [[6]
  [8]]]
