In [10]:
import numpy as np

In [11]:
# the basics

a = np.array([1, 2, 3] , dtype = 'int32')
print(a)

[1 2 3]


In [12]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [13]:
a.nbytes # getdim the total number of bytes consumed by the elements of the array

12

In [14]:
a.ndim

1

In [15]:
a.dtype

dtype('int32')

In [16]:
b.shape 

(2, 3)

In [19]:
a.nbytes

12

In [18]:
a.itemsize

4