In [3]:
import numpy as np  

In [ ]:
#ALL 0 MATRIX
np.zeros((3, 3 ,3))

In [ ]:
np.ones((3, 3 ,3))

In [12]:
np.full((3, 3, 3), 5)

array([[[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]]])

In [13]:
np.random.rand(3, 3)

array([[0.98539617, 0.84595904, 0.22897344],
       [0.98366574, 0.37858311, 0.92137853],
       [0.94467892, 0.23291966, 0.78195752]])

In [14]:
np.random.randint(1, 100, (3, 3))

array([[15, 81, 95],
       [61, 55, 23],
       [13, 72,  3]])

In [15]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr , 3 , axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [33]:
arr = np.zeros((5,5))
arr[[0,-1],:] = 1 #->arr[[row_start,row_end]:] 
arr[:,[0,-1]] = 1
arr[2,2] = 9
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
