In [19]:
import numpy as np

In [20]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [21]:
a +=2

In [22]:
b = np.array([1,2,3,4,5,6])
b -= 2
b

array([-1,  0,  1,  2,  3,  4])

In [23]:
c = np.array([1,2,3,4,5,6,7])
c *= 2
c

array([ 2,  4,  6,  8, 10, 12, 14])

In [24]:
x = np.array([[16,23,43],[14,45,56],[27,38,19]])

print(np.linalg.det(x))


-21078.999999999993


In [44]:
y = np.arange(start=1 , stop=13 , step=1)
z = y.reshape(3,4)
print(z)
q = z[:,2:]
q


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 3,  4],
       [ 7,  8],
       [11, 12]])